### ISSUE TITLE
编辑时删除封面图提交后封面仍然在

### ISSUE THREAD

**Issue by lonsn2** [inbjo/CoreBlog#11]
上传封面图后，发现在文章列表页面图片太大，会造成以为是文章内容的错觉，在编辑中删除封面图片提交后，发现封面仍然存在，永远无法删除，清除缓存也是一样。

**Comment by inbjo** [comment]
已修复 https://github.com/inbjo/CoreBlog/commit/d5289101876de354b8af2a58833b802d3e7f9a4e
