### ISSUE TITLE
第一次给文章加标签，提交后标签丢失

### ISSUE THREAD

**Issue by lonsn2** [inbjo/CoreBlog#12]
习惯性地输入标签后用逗号分开，提交后发现标签丢失，后来发现输入每个标签后需要按回车键，标签会变成绿色才可以成为标签。虽然教程图上面标注了输入标签需要按回车，但没有仔细看会忽略，建议在“文章标签”后面增加一条说明：文章标签（输入每个标签后按回车）

**Comment by inbjo** [comment]
![image](https://user-images.githubusercontent.com/11854149/84101575-da944380-aa40-11ea-9119-2401fea633ee.png)
鼠标放到文章标签上面是有提示的
