### ISSUE TITLE
No application encryption key has been specified

### ISSUE THREAD

**Issue by bruceqiq** [inbjo/CoreBlog#2]
No application encryption key has been specified.

(1/1) RuntimeExceptionNo application encryption key has been specified.
--
in EncryptionServiceProvider.php line 44
at EncryptionServiceProvider->Illuminate\Encryption\{closure}('')in helpers.php line 1124

已经创建了APP_KEY键了，还是提示上面的错误，根据错误排查了问题，就是.env配置的键存在空。博主中.env文件有很多配置项，还是希望出一个相对完善的一个文档吧。既然都是开源出来了，就得让用的人很快看明白吧。

**Comment by inbjo** [comment]
检查一下`.env`中`APP_KEY`是否存在值，如果不存在请在项目根目录执行`php artisan key:generate`。
如果你执行过`php artisan blog:install`会自动执行上述命令的。
文档已经添加https://www.inbjo.com/docs (还在完善中)

**Comment by bruceqiq** [comment]
已经执行过了，问题仍然报该错误。




On 08/02/2019 10:45, Flex wrote:

检查一下.env中APP_KEY是否存在值，如果不存在请在项目根目录执行php artisan key:generate。
如果你执行过php artisan blog:install会自动执行上述命令的。
文档已经添加https://www.inbjo.com/docs (还在完善中)

**Comment by inbjo** [comment]
麻烦你把你的`.env`贴上来看看

**Comment by bruceqiq** [comment]
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:1kMfP0tcaHwANv0KTKCch4/wypw0rlGBIX+Z2t2U/eQ=
APP_DEBUG=true
APP_URL=http://localhost


SITE_NAME=CoreBlog
SITE_SLOGAN=an-elegant-blog-system
SITE_KEYWORD=CoreBlog,Blog,Laravel
SITE_DESCRIPTION=CoreBlog-an-elegant-blog-system
SITE_ICP=京ICP证030173号
SITE_POLICE=京公网安备11000002000001号


LOG_CHANNEL=stack


DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=


BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120


SCOUT_DRIVER=tntsearch
TNTSEARCH_TOKENIZER=jieba


REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379


MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME=CoreBlog
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null


ALI_APP_ID=
ALI_PUBLIC_KEY=
ALI_PRIVATE_KEY=


WECHAT_APP_ID=
WECHAT_MCH_ID=
WECHAT_KEY=


OSS_ACCESS_KEY=
OSS_SECRET_KEY=
OSS_ENDPOINT=
OSS_BUCKET=






在 2019-08-02 15:05:09，"Flex" <notifications@github.com> 写道：


麻烦你把你的.env贴上来看看

**Comment by inbjo** [comment]
> APP_NAME=Laravel APP_ENV=local APP_KEY=base64:1kMfP0tcaHwANv0KTKCch4/wypw0rlGBIX+Z2t2U/eQ= APP_DEBUG=true APP_URL=http://localhost SITE_NAME=CoreBlog SITE_SLOGAN=an-elegant-blog-system SITE_KEYWORD=CoreBlog,Blog,Laravel SITE_DESCRIPTION=CoreBlog-an-elegant-blog-system SITE_ICP=京ICP证030173号 SITE_POLICE=京公网安备11000002000001号 LOG_CHANNEL=stack DB_CONNECTION=mysql DB_HOST=127.0.0.1 DB_PORT=3306 DB_DATABASE= DB_USERNAME= DB_PASSWORD= BROADCAST_DRIVER=log CACHE_DRIVER=file QUEUE_CONNECTION=sync SESSION_DRIVER=file SESSION_LIFETIME=120 SCOUT_DRIVER=tntsearch TNTSEARCH_TOKENIZER=jieba REDIS_HOST=127.0.0.1 REDIS_PASSWORD=null REDIS_PORT=6379 MAIL_DRIVER=smtp MAIL_HOST=smtp.mailtrap.io MAIL_FROM_ADDRESS=hello@example.com MAIL_FROM_NAME=CoreBlog MAIL_PORT=2525 MAIL_USERNAME=null MAIL_PASSWORD=null MAIL_ENCRYPTION=null ALI_APP_ID= ALI_PUBLIC_KEY= ALI_PRIVATE_KEY= WECHAT_APP_ID= WECHAT_MCH_ID= WECHAT_KEY= OSS_ACCESS_KEY= OSS_SECRET_KEY= OSS_ENDPOINT= OSS_BUCKET= 在 2019-08-02 15:05:09，"Flex" <notifications@github.com> 写道： 麻烦你把你的.env贴上来看看 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

从配置上看并没有什么大问题，请将CACHE_DRIVER和SESSION_DRIVER改为redis。如果还在存在疑问请加我扣扣:14三个零1三个零8。
