### ISSUE TITLE
php artisan blog:install

### ISSUE THREAD

**Issue by mansfields** [inbjo/CoreBlog#4]
Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18

**Comment by inbjo** [comment]
你是通过git克隆方式安装的吧？需要在项目根目录执行`Composer install`安装依赖包
